#!/usr/bin/env bash
set -euo pipefail

# Interactive disk cleanup helper for Debian/Ubuntu.
# It scans common "usually safe to clean" targets, explains each item,
# then lets the user choose what to delete.
#
# Usage:
#   sudo bash disk_cleanup_select.sh
#
# Optional env vars:
#   MAX_CANDIDATES=500
#   MIN_TMP_AGE_DAYS=7
#   MIN_TMP_SIZE_MB=1
#   MIN_PATTERN_SIZE_MB=10
#   CACHE_DIR_THRESHOLD_MB=200

MAX_CANDIDATES="${MAX_CANDIDATES:-500}"
MIN_TMP_AGE_DAYS="${MIN_TMP_AGE_DAYS:-7}"
MIN_TMP_SIZE_MB="${MIN_TMP_SIZE_MB:-1}"
MIN_PATTERN_SIZE_MB="${MIN_PATTERN_SIZE_MB:-10}"
CACHE_DIR_THRESHOLD_MB="${CACHE_DIR_THRESHOLD_MB:-200}"

WORK_DIR="$(mktemp -d /tmp/disk-cleanup.XXXXXX)"
RAW_FILE="$WORK_DIR/candidates.tsv"
SORTED_FILE="$WORK_DIR/candidates.sorted.tsv"
trap 'rm -rf "$WORK_DIR"' EXIT

touch "$RAW_FILE"

declare -A SEEN=()
declare -a ITEM_KIND=()
declare -a ITEM_PATH=()
declare -a ITEM_SIZE=()
declare -a ITEM_REASON=()
declare -a ITEM_ORIGIN=()
declare -a SELECTED_INDEXES=()

CANDIDATE_COUNT=0

log() {
  printf '[%s] %s\n' "$(date '+%F %T')" "$*"
}

human_size() {
  local bytes="${1:-0}"
  if command -v numfmt >/dev/null 2>&1; then
    numfmt --to=iec-i --suffix=B "$bytes" 2>/dev/null || echo "${bytes}B"
  else
    echo "${bytes}B"
  fi
}

size_of_path() {
  local path="$1"
  if [[ -f "$path" || -L "$path" ]]; then
    stat -c '%s' "$path" 2>/dev/null || echo 0
    return
  fi
  if [[ -d "$path" ]]; then
    du -sb "$path" 2>/dev/null | awk '{print $1}' || echo 0
    return
  fi
  echo 0
}

add_candidate() {
  local kind="$1"      # FILE | DIR
  local path="$2"
  local size="$3"
  local reason="$4"
  local origin="$5"
  local key

  (( CANDIDATE_COUNT < MAX_CANDIDATES )) || return 0
  [[ -n "$path" ]] || return 0

  key="${kind}::${path}"
  if [[ -n "${SEEN[$key]:-}" ]]; then
    return 0
  fi
  SEEN["$key"]=1

  printf '%s\t%s\t%s\t%s\t%s\n' "$size" "$kind" "$path" "$reason" "$origin" >> "$RAW_FILE"
  CANDIDATE_COUNT=$((CANDIDATE_COUNT + 1))
}

collect_apt_cache() {
  local f size
  local dir="/var/cache/apt/archives"
  [[ -d "$dir" ]] || return 0

  while IFS= read -r -d '' f; do
    size="$(size_of_path "$f")"
    add_candidate \
      "FILE" \
      "$f" \
      "$size" \
      "APT downloaded package cache; can be re-downloaded." \
      "Generated by apt/apt-get install or upgrade."
  done < <(find "$dir" -maxdepth 1 -type f -name '*.deb' -print0 2>/dev/null)
}

collect_rotated_logs() {
  local f size
  local dir="/var/log"
  [[ -d "$dir" ]] || return 0

  while IFS= read -r -d '' f; do
    size="$(size_of_path "$f")"
    add_candidate \
      "FILE" \
      "$f" \
      "$size" \
      "Rotated/compressed log file, usually historical logs." \
      "Generated by services and logrotate."
  done < <(find "$dir" -xdev -type f \( -name '*.gz' -o -name '*.1' -o -name '*.old' -o -name '*.log.*' \) -size +5M -print0 2>/dev/null)
}

collect_tmp_files() {
  local dir f size
  for dir in /tmp /var/tmp; do
    [[ -d "$dir" ]] || continue
    while IFS= read -r -d '' f; do
      size="$(size_of_path "$f")"
      add_candidate \
        "FILE" \
        "$f" \
        "$size" \
        "Old temporary file." \
        "Generated by applications during runtime."
    done < <(find "$dir" -xdev -type f -mtime +"$MIN_TMP_AGE_DAYS" -size +"${MIN_TMP_SIZE_MB}"M -print0 2>/dev/null)
  done
}

collect_crash_dumps() {
  local f size
  local dir="/var/crash"
  [[ -d "$dir" ]] || return 0

  while IFS= read -r -d '' f; do
    size="$(size_of_path "$f")"
    add_candidate \
      "FILE" \
      "$f" \
      "$size" \
      "Crash dump file." \
      "Generated when a process/service crashes."
  done < <(find "$dir" -xdev -type f -print0 2>/dev/null)
}

collect_user_trash() {
  local d size
  for d in /root/.local/share/Trash/files /home/*/.local/share/Trash/files; do
    [[ -d "$d" ]] || continue
    size="$(size_of_path "$d")"
    add_candidate \
      "DIR" \
      "$d" \
      "$size" \
      "Desktop trash folder." \
      "Generated by file manager delete operations."
  done
}

collect_known_cache_dirs() {
  local d size
  local -a paths=(
    /root/.cache
    /root/.npm
    /root/.cache/pip
    /root/.cache/yarn
    /root/.cache/pnpm
    /root/.cache/go-build
    /root/.cargo/registry
    /root/.cargo/git
  )

  for d in /home/*/.cache /home/*/.npm /home/*/.cache/pip /home/*/.cache/yarn /home/*/.cache/pnpm /home/*/.cache/go-build /home/*/.cargo/registry /home/*/.cargo/git; do
    paths+=("$d")
  done

  for d in "${paths[@]}"; do
    [[ -d "$d" ]] || continue
    size="$(size_of_path "$d")"
    if (( size < CACHE_DIR_THRESHOLD_MB * 1024 * 1024 )); then
      continue
    fi

    add_candidate \
      "DIR" \
      "$d" \
      "$size" \
      "Package/application cache directory (usually regenerable)." \
      "Generated by pip/npm/yarn/pnpm/go/cargo/browser or app runtime."
  done
}

collect_pattern_files_across_disk() {
  local root f size
  local -a scan_roots=()

  if command -v findmnt >/dev/null 2>&1; then
    while IFS= read -r root; do
      [[ -n "$root" ]] && scan_roots+=("$root")
    done < <(findmnt -rn -o TARGET,FSTYPE | awk '$2 ~ /^(ext2|ext3|ext4|xfs|btrfs|f2fs|zfs)$/ {print $1}' | sort -u)
  fi
  if (( ${#scan_roots[@]} == 0 )); then
    scan_roots=(/)
  fi

  for root in "${scan_roots[@]}"; do
    while IFS= read -r -d '' f; do
      size="$(size_of_path "$f")"
      add_candidate \
        "FILE" \
        "$f" \
        "$size" \
        "Large temp/backup-like file by extension (*.tmp/*.bak/*.old/*~)." \
        "Likely created by editors/tools/scripts during edits or backup."
    done < <(
      find "$root" -xdev \
        \( -path '/proc' -o -path '/sys' -o -path '/dev' -o -path '/run' -o -path '/snap' -o -path '/var/lib/docker' -o -path '/var/lib/containerd' \) -prune -o \
        -type f \
        \( -name '*.tmp' -o -name '*.bak' -o -name '*.old' -o -name '*~' \) \
        -mtime +"$MIN_TMP_AGE_DAYS" \
        -size +"${MIN_PATTERN_SIZE_MB}"M \
        -print0 2>/dev/null
    )
  done
}

build_item_arrays() {
  local size kind path reason origin
  sort -nr -k1,1 "$RAW_FILE" > "$SORTED_FILE"

  while IFS=$'\t' read -r size kind path reason origin; do
    ITEM_SIZE+=("${size:-0}")
    ITEM_KIND+=("$kind")
    ITEM_PATH+=("$path")
    ITEM_REASON+=("$reason")
    ITEM_ORIGIN+=("$origin")
  done < "$SORTED_FILE"
}

print_candidates() {
  local i idx hsize total
  total="${#ITEM_PATH[@]}"
  echo
  echo "Found $total candidate items:"
  for i in "${!ITEM_PATH[@]}"; do
    idx=$((i + 1))
    hsize="$(human_size "${ITEM_SIZE[$i]}")"
    printf '%3d) [%s] %s (%s) (%s; source: %s)\n' \
      "$idx" \
      "${ITEM_KIND[$i]}" \
      "${ITEM_PATH[$i]}" \
      "$hsize" \
      "${ITEM_REASON[$i]}" \
      "${ITEM_ORIGIN[$i]}"
  done
}

parse_selection() {
  local input token idx
  local -a tokens=()
  declare -A picked=()

  read -r -p "Select indexes to delete (example: 1,3,8 or all): " input
  input="$(echo "$input" | xargs)"

  if [[ -z "$input" ]]; then
    echo "Empty selection, exit."
    exit 1
  fi

  if [[ "$input" == "all" || "$input" == "ALL" ]]; then
    for idx in "${!ITEM_PATH[@]}"; do
      picked["$idx"]=1
    done
  else
    input="${input// /}"
    IFS=',' read -r -a tokens <<< "$input"
    for token in "${tokens[@]}"; do
      [[ -n "$token" ]] || continue
      if [[ ! "$token" =~ ^[0-9]+$ ]]; then
        echo "Invalid index: $token"
        exit 1
      fi
      idx=$((token - 1))
      if (( idx < 0 || idx >= ${#ITEM_PATH[@]} )); then
        echo "Index out of range: $token"
        exit 1
      fi
      picked["$idx"]=1
    done
  fi

  mapfile -t SELECTED_INDEXES < <(printf '%s\n' "${!picked[@]}" | sort -n)
  if (( ${#SELECTED_INDEXES[@]} == 0 )); then
    echo "No items selected, exit."
    exit 1
  fi
}

is_safe_delete_target() {
  local kind="$1"
  local path="$2"
  local depth

  [[ -n "$path" ]] || return 1
  [[ "$path" != "/" ]] || return 1
  [[ "$path" != "/root" ]] || return 1
  [[ "$path" != "/home" ]] || return 1
  [[ "$path" != "/var" ]] || return 1
  [[ "$path" != "/usr" ]] || return 1
  [[ "$path" != "/etc" ]] || return 1
  [[ "$path" != "/var/lib/docker" ]] || return 1
  [[ "$path" != "/var/lib/containerd" ]] || return 1

  if [[ "$kind" == "DIR" ]]; then
    depth="$(awk -F'/' '{print NF-1}' <<< "$path")"
    (( depth >= 2 )) || return 1
  fi

  return 0
}

show_delete_plan() {
  local idx i sum hsum
  sum=0
  echo
  echo "Deletion plan:"
  for idx in "${SELECTED_INDEXES[@]}"; do
    i="$idx"
    sum=$((sum + ITEM_SIZE[i]))
    printf '  - [%s] %s (%s)\n' \
      "${ITEM_KIND[i]}" \
      "${ITEM_PATH[i]}" \
      "$(human_size "${ITEM_SIZE[i]}")"
  done
  hsum="$(human_size "$sum")"
  echo "Estimated reclaimable size: $hsum"
}

delete_selected() {
  local idx i kind path
  local deleted=0 skipped=0 failed=0

  for idx in "${SELECTED_INDEXES[@]}"; do
    i="$idx"
    kind="${ITEM_KIND[i]}"
    path="${ITEM_PATH[i]}"

    if ! is_safe_delete_target "$kind" "$path"; then
      log "Skip unsafe target: [$kind] $path"
      skipped=$((skipped + 1))
      continue
    fi

    if [[ "$kind" == "FILE" ]]; then
      if [[ -e "$path" || -L "$path" ]]; then
        if rm -f -- "$path"; then
          log "Deleted file: $path"
          deleted=$((deleted + 1))
        else
          log "Delete failed: $path"
          failed=$((failed + 1))
        fi
      else
        log "Skip missing file: $path"
        skipped=$((skipped + 1))
      fi
    elif [[ "$kind" == "DIR" ]]; then
      if [[ -d "$path" ]]; then
        if rm -rf -- "$path"; then
          log "Deleted directory: $path"
          deleted=$((deleted + 1))
        else
          log "Delete failed: $path"
          failed=$((failed + 1))
        fi
      else
        log "Skip missing directory: $path"
        skipped=$((skipped + 1))
      fi
    fi
  done

  echo
  echo "Done. deleted=$deleted skipped=$skipped failed=$failed"
}

main() {
  if [[ "${EUID:-$(id -u)}" -ne 0 ]]; then
    echo "Run as root for full-disk scan and cleanup."
    exit 1
  fi

  log "Scanning candidates..."
  collect_apt_cache
  collect_rotated_logs
  collect_tmp_files
  collect_crash_dumps
  collect_user_trash
  collect_known_cache_dirs
  collect_pattern_files_across_disk

  if [[ ! -s "$RAW_FILE" ]]; then
    echo "No cleanup candidates found."
    exit 0
  fi

  build_item_arrays
  print_candidates
  parse_selection
  show_delete_plan

  echo
  echo "Type DELETE to confirm actual deletion."
  read -r -p "> " confirm
  if [[ "$confirm" != "DELETE" ]]; then
    echo "Canceled."
    exit 0
  fi

  delete_selected
}

main "$@"
